/** Central dictionary for reusable user-facing application copy. */
export const DIC = {
  appName: "Socially",
  auth: {
    welcomeBack: "Welcome back",
    loginSubtitle: "Enter your credentials to access your account",
    createAccount: "Create an account",
    registerSubtitle: "Join the developer community on Socially",
    email: "Email",
    password: "Password",
    fullName: "Full Name",
    emailRequired: "Email is required",
    invalidEmail: "Invalid email address",
    passwordRequired: "Password is required",
    passwordMinLength: "Password must be at least 6 characters",
    emailPlaceholder: "name@example.com",
    namePlaceholder: "Farshad Hosseini",
    passwordPlaceholder: "••••••••",
    login: "Sign In",
    register: "Create Account",
    signUpPrompt: "Don't have an account?",
    signUp: "Sign up",
    loginPrompt: "Already have an account?",
    logIn: "Log in",
    loginError: "Login failed. Please try again.",
    registrationError: "Registration failed. Please try again.",
    welcomeToast: "Welcome back!",
    accountCreatedToast: "Account created successfully",
    showPassword: "Show password",
    hidePassword: "Hide password",
  },
  navigation: {
    home: "Home",
    notifications: "Notifications",
    profile: "Profile",
    menu: "Menu",
    logOut: "Log Out",
    toggleTheme: "Toggle theme",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    unreadNotifications: "Unread notifications",
  },
  loading: { default: "Loading...", pleaseWait: "Please wait" },
  notFound: {
    title: "Page not found",
    description: "Sorry, we couldn’t find the page you’re looking for.",
    goHome: "Go back home",
  },
  profile: {
    posts: "Posts",
    likes: "Likes",
    follow: "Follow",
    unfollow: "Unfollow",
    noWebsite: "No website",
    noLocation: "No location",
  },
  search: { placeholder: "Search users...", users: "Search users" },
  post: {
    composerPlaceholder: "What's on your mind?",
    commentPlaceholder: "Write a comment...",
    signInToLike: "Please sign in to like this post.",
    ownPostLike: "You cannot like your own post.",
    deletePost: "Delete Post",
    deleteComment: "Delete Comment",
    deleteDescription: "This action cannot be undone.",
    deleteCommentDescription: "Are you sure you want to delete this comment?",
  },
  errors: {
    generic: "Something went wrong",
    timeout: "Request timed out. Please try again.",
    network: "Network error. Please check your connection.",
    server: "Server error. Please try again later.",
    requestFailed: "Request failed",
  },
} as const;

/** Backward-compatible alias for existing imports. */
export const UI_STRINGS = DIC;
