#!/bin/sh
# File: Prevents commits directly on protected branches.

branch_name=$(git branch --show-current)

if [ -z "$branch_name" ]; then
  echo "❌ Cannot detect current branch."
  exit 1
fi

case "$branch_name" in
  main|develop|deploy)
    echo "❌ You cannot commit on '$branch_name' branch."
    exit 1
    ;;
esac

exit 0
